### ISSUE TITLE
Question about timing shift

### ISSUE THREAD

**Issue by lizhenqianri** [cloud9477/gr-advoqpsk#1]
Hello, I have been following this project. I found that after adding the Channal Model module, setting some time offset can cause a wide range of bit errors. Excuse me, is there any solution?
![Uploading 20221213160517.png…]()

**Comment by cloud9477** [comment]
I wonder if you solved it, the uploaded figure is not accessable.

**Comment by lizhenqianri** [comment]
> 

not solved
![2](https://user-images.githubusercontent.com/89636602/207763946-c43f3ffa-e301-4d2c-9446-c5f1ec7af0c1.png)
![20221213160517](https://user-images.githubusercontent.com/89636602/207763953-1f6f8d42-ee01-406d-bd6e-f61985ad764b.png)

**Comment by lizhenqianri** [comment]
my flowchart @cloud9477 
![333330221215112017](https://user-images.githubusercontent.com/89636602/207764758-4ccb9007-c47b-4caf-beb6-a86db239d652.png)

**Comment by cloud9477** [comment]
I just checked the channel model block, it says that the freq offset is a normalized number, I think the 1e3 is too large, maybe you could try to first set the freq offset to be a reasonable value.

**Comment by lizhenqianri** [comment]
But I set the frequency offset to 0, and only set the time offset, but the packet loss is still serious. I think the problem is caused by time offset, long-distance transmission will cause time offset.
![33333](https://user-images.githubusercontent.com/89636602/207831322-605f6e37-28b0-4fdd-b079-cf7607d9fce3.png)

**Comment by lizhenqianri** [comment]
thanks, @cloud9477 .
The first time I discovered this problem was when B210+BUC was used for long-distance communication, and it was found that it might be caused by time offset, so I used gnuradio to perform a time offset simulation test (frequency offset was set to 0), and the test results were consistent . When sending 100 bytes, the received data starts to error at about 60 bytes.

**Comment by cloud9477** [comment]
I checked the channel model and the epsilon should be the sampling time offset which will mainly increase the freq offset and I guess it may be even larger than the requirement of the standard for the receiver to handle. However I don't think this relates to long distance transmissions since distance only attenuates the signal power.
